### ISSUE TITLE
corsica scraper scripts are dead

### ISSUE THREAD

**Issue by sebastian-burlacu** [evolvingwild/hockey-all#1]
(I don't have twitter else I would ping you there)

The linked corsica scraper scripts are gone as manny has taken his site and code off the internet. I'm working on how to query and parse NHL data via the API, but how would I ensure I get it into a good format to use with your scripts?

Thanks for putting your work out there, I'm learning a lot from it.

**Comment by evolvingwild** [comment]
We're sorry we missed this. Manny did take his scraper down so this code is deprecated - we are closing this issue. Sorry for any inconvenience.
